### PR TITLE
Use GOTMPDIR env to clean all the go-build folders

### LINKED ISSUE #182: When a TIMED OUT occur we do not clean the go-build* folder in /tmp
When we call the `go test` it first builds all the files needed to run the tests. The build artifacts are created under /tmp dir by default and have a name like `go-build19625282`. 

Every time we kill the execution of `go test` it does not clean the build directory created under the /tmp dir. This means that every time we have a mutation that goes on TIMED_OUT we do not clear the relative build dirs.

Step I did to reproduce:

1. rm -rf /tmp/go-build*
2. gremlin unleash | grep "TIMED OUT" | wc -l
3. ls /tmp | grep go-build | wc -l

## Solution

Set the `GOTMPDIR` env var that will be used by `go test` to store all the build dirs of gremlins. Clean up that folder before quitting `gremlins`.

### PR DESCRIPTION
**Pull request by alessio-perugini**
## Proposed changes

Closes #182. 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/go-gremlins/gremlins/docs/CONTRIBUTING.md) doc
- [x] Lint and unit tests pass locally with my changes (`make all`)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

The proposed PR is an idea to overcome the issue of not cleaning build folders when going into time out.
Writing the test it felt a bit awkward the way I got the root dir of our `wdDealer`. I think in writing this line: 
```go
goTmpDirEnv := fmt.Sprintf("GOTMPDIR=%s", filepath.Dir(mut.Workdir()))
```
I'm leaking implementation logic in our test.

So I was thinking of another way to get the same result in a cleaner way. We might add a new func in the `Dealer interface`  that returns the root working directory.
```go
type Dealer interface {
	Get(idf string) (string, error)
	WorkDir() string
	Clean()
}
```
Introduction the `WorkDir()` getter we can also refactor the implementation in just this 2 lines:
```go
	cmd.Env = append(cmd.Env, os.Environ()...)
	cmd.Env = append(cmd.Env, fmt.Sprintf("GOTMPDIR=" +m.wdDealer.WorkDir()))
```

WDYT? Should I do the proposed refactoring? Do you suggest other improvements/solutions?

### CODE REVIEW

**Comment by k3rn31** [comment]
Thanks for the PR. I'd do the refactoring, I don't think we need it in the mutator.

Do you think this also closes #177?

**Comment by alessio-perugini** [comment]
@k3rn31 
- So should we call the `os.Setenv("GOTMPDIR", workDir)` in the cmd/unleash.go:9 and in the mutator just keep the `	cmd.Env = append(cmd.Env, os.Environ()...)` ?

- Nope unfortunately it doesn't close the #177. I've tried to inject the `GOCACHE` as I did with the `GOTMPDIR` but it leads to only TIMEOUT results

**Comment by k3rn31** [comment]
No, I meant the second approach where the Dealer gives the root. Seems cleaner, so we set it just once, but it is explicit that the temp dir is modified when we call the command. 
I prefer that it is explicit we are setting the env variable when we call the command, otherwise it might not be clear and someone can easily introduce bugs there, not knowing.

**Review by k3rn31 — CHANGES_REQUESTED** [review]
We should add a test to the dealer for WorkDir to be consistent.

File: internal/engine/executor.go [hunk 1]
```diff
@@ -199,6 +200,8 @@ func (m *mutantExecutor) runTests(pkg string) mutator.Status {
 
 	cmd := m.execContext(ctx, "go", m.getTestArgs(pkg)...)
 	cmd.Dir = m.mutant.Workdir()
+	cmd.Env = append(cmd.Env, os.Environ()...)
```
Comment (k3rn31) [inline internal/engine/executor.go:203]: Wouldn't be better to do `cmd.Env = os.Environ`. Not sure, but I think we can spare an array allocation. 

At the beginning Env should be nil, in the first append, it allocates an array with the length of Environ. Then, in the second array it reallocates for the added element, isn't it?
If we assign Environ directly, we are sure at most it reallocates in the only append we have. I'm not certain my reasoning is correct though :smile:. What do you thin?

File: internal/engine/executor_test.go [hunk 2]
```diff
@@ -461,6 +461,53 @@ func TestMutatorRunInTheCorrectFolder(t *testing.T) {
 	})
 }
 
+func TestMutatorRunWithCorrectEnvs(t *testing.T) {
```
Comment (k3rn31) [inline internal/engine/executor_test.go:464]: Maybe this test can be integrated in the `TestMutatorTestExecution`, they are almost identical.

**Review by k3rn31 — CHANGES_REQUESTED** [review]
I added a couple of comments. Please, check if they make sense to you, otherwise we can proceed with the merge.

File: internal/engine/executor.go (hunk 1 above)
Comment (alessio-perugini) [reply internal/engine/executor.go:203]: The only reason I did that is to not break test in: `TestMutatorTestExecution`. In the `executor_test.go:557` we set the `GO_TEST_PROCESS=1` if we do not append we will override that breaking 2 tests.

About the allocation, since the os.Environ should be more or less the same every time we call it (at least the env vars we need). We might want to refactor where we assign that line.
We can create our custom execContext func that pre-allocates the env vars, so we will do the allocation and the sys call only once, and not every time we call the `runTests` func:

```go
func NewExecutorDealer(mod gomodule.GoModule, wdd workdir.Dealer, elapsed time.Duration, opts ...ExecutorDealerOption) *MutantExecutorDealer {
...
	jd := MutantExecutorDealer{
                ...
		execContext:       commandWithEnvs,
	}
...
}
func commandWithEnvs(ctx context.Context, name string, arg ...string) *exec.Cmd {
	cmd := exec.CommandContext(ctx, name, arg...)
	cmd.Env = os.Environ()
	return cmd
}

```

Comment (k3rn31) [reply internal/engine/executor.go:203]: Even if the env is set at every mutator run (potentially a lot of times) I was concerned, but maybe what we gain not reallocating is marginal and doesn't justify this refactoring, what do you think?

Comment (alessio-perugini) [reply internal/engine/executor.go:203]: We should perform some benchmarks. I think it won't be the most expensive operation we're doing so we should be fine for now running that code for every mutator.

**Review by k3rn31 — APPROVED** [review]
